# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'idus-test-iOS-Aizen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for idus-test-iOS-Aizen
  pod 'Alamofire'
  pod 'XLPagerTabStrip', '~> 9.0'

end
